/* eslint-disable */
// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Fetch the curated registry, with offline fallback to cache/bundled snapshot.
 */
async getRegistry() : Promise<Result<RegistryResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_registry") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the skills installed under a target, each with its conformance verdict.
 */
async listSkills(target: TargetKind) : Promise<Result<SkillDescriptor[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Evaluate raw SKILL.md text against the spec (used for previews/Craft).
 */
async checkConformance(skillMd: string, parentDirName: string) : Promise<Conformance> {
    return await TAURI_INVOKE("check_conformance", { skillMd, parentDirName });
},
/**
 * Install a skill from a local directory into a target. This is the working
 * install path for I-1 (the `SkillSource` abstraction). A GitHub-fetching
 * source — installing directly from a registry entry — is the follow-on.
 */
async installLocalSkill(sourceDir: string, target: TargetKind) : Promise<Result<SkillDescriptor, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_local_skill", { sourceDir, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveTarget(target: TargetKind) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_target", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveTarget() : Promise<Result<TargetKind | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_target") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report skill usage parsed from the local Claude Code transcripts under
 * `~/.claude/projects/`, grouped by project, and joined against the skills
 * installed in the global target (plus the active project target, if one is
 * set) so never-used installed skills are visible. Read-only (I-2 / P-5).
 */
async getUsage() : Promise<Result<UsageView, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_usage") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * IPC-facing error. Mirrors `AppError` but is `Serialize + specta::Type`.
 */
export type CommandError = { kind: string; message: string; 
/**
 * Present only for validation failures, so the UI can show why a skill
 * was rejected.
 */
conformance: Conformance | null }
export type Conformance = { verdict: Verdict; findings: Finding[] }
/**
 * A single conformance issue. `code` is a stable machine identifier
 * (e.g. `name.dir_mismatch`); `message` is human-facing.
 */
export type Finding = { field: string; severity: Severity; code: string; message: string }
/**
 * An installed skill alongside its total invocations across all projects.
 * `total == 0` means the skill is installed but never recorded as used.
 */
export type InstalledUsage = { skill: string; total: number }
/**
 * Per-skill invocation counts for a single project (working directory).
 */
export type ProjectUsage = { 
/**
 * The project working directory (the transcript `cwd`).
 */
project: string; 
/**
 * Total invocations across every skill in this project.
 */
total: number; 
/**
 * Per-skill counts, sorted by count desc then skill name asc.
 */
skills: SkillCount[] }
/**
 * One installable skill advertised by the registry.
 */
export type RegistryEntry = { name: string; description: string; 
/**
 * `owner/name` of the hosting repo.
 */
repo: string; 
/**
 * Path to the skill directory within the repo, if not the repo root.
 */
subdir: string | null; 
/**
 * Tag/branch/sha; the repo's default branch when `None`.
 */
git_ref: string | null; featured: boolean }
export type RegistryManifest = { schema_version: number; generated_at: string; entries: RegistryEntry[] }
export type RegistryResult = { manifest: RegistryManifest; source: RegistrySource }
/**
 * Where the manifest the UI is showing actually came from. Lets the shop tell
 * the user it is running on cached/offline data.
 */
export type RegistrySource = "network" | "cache" | "bundled"
export type Severity = "error" | "warning"
/**
 * How many times one skill was invoked.
 */
export type SkillCount = { skill: string; count: number }
/**
 * A skill as seen on disk (or about to be installed), with its conformance
 * verdict attached so the shop/library can render a badge (Outcome 2).
 */
export type SkillDescriptor = { 
/**
 * Frontmatter `name`, falling back to the directory name if absent.
 */
name: string; 
/**
 * The actual on-disk directory name.
 */
dir_name: string; path: string; description: string | null; conformance: Conformance }
export type TargetKind = 
/**
 * A project directory; skills live under `<project>/.claude/skills`.
 */
{ kind: "project"; path: string } | 
/**
 * The user's global skills under `<home>/.claude/skills`.
 */
{ kind: "global" }
/**
 * The Usage screen's view: per-project invocation counts (the I-2 outcome),
 * plus installed skills annotated with their total invocations so unused ones
 * (total 0) surface for pruning.
 */
export type UsageView = { projects: ProjectUsage[]; installed: InstalledUsage[] }
export type Verdict = "valid" | "warnings" | "invalid"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
