//! Tauri shell entry point. Wires the IPC command surface, generates the
//! TypeScript bindings (in debug builds), injects the live HTTP registry
//! fetcher, and resolves the app-data + home directories into shared state.

mod commands;
mod http_fetcher;
mod http_skill_fetcher;
mod state;

use http_fetcher::HttpFetcher;
use http_skill_fetcher::HttpSkillFetcher;
use state::AppState;
use tauri::Manager;

/// Curated-catalog source: the raw content of a public, read-only GitHub gist
/// (I-5). A gist is editable without an app release and needs no auth, and the
/// `/raw` URL always serves the latest revision.
///
/// PLACEHOLDER: the canonical gist id is not yet provisioned — swap `GIST_ID`
/// for the real one when it exists. Until then this resolves to a 404, which
/// `get_registry` treats as unreachable: the shop serves the on-disk cache or
/// the bundled snapshot and stays usable offline.
const REGISTRY_URL: &str =
    "https://gist.githubusercontent.com/agentskills/GIST_ID/raw/catalog.json";

/// GitHub Contents API base, used by the shop's GitHub-fetch install to pull a
/// registry entry's skill files. Unauthenticated + read-only (no secrets).
const GITHUB_API_BASE: &str = "https://api.github.com";

pub fn run() {
    // tauri-specta builder: single source of truth for the command set and the
    // generated TS bindings.
    let builder = tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        commands::get_registry,
        commands::list_skills,
        commands::check_conformance,
        commands::install_local_skill,
        commands::install_registry_skill,
        commands::read_skill,
        commands::publish_skill,
        commands::set_active_target,
        commands::get_active_target,
        commands::get_usage,
    ]);

    // Regenerate the frontend bindings on every debug build so TS can never
    // drift from the Rust commands.
    #[cfg(debug_assertions)]
    builder
        .export(
            // `total: u64` (usage counts) maps to a TS `number`: Tauri IPC
            // serializes via serde_json, which emits u64 as a JSON number, so
            // `number` matches the wire format. specta's default (Fail) aborts
            // on any bigint type.
            // Prepend a lint/typecheck opt-out: the file is generated boilerplate
            // (unused channel/event helpers, `any`-typed internals) that otherwise
            // trips the project's `tsc --noUnusedLocals` and eslint rules.
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .remove_default_header()
                .header(
                    "/* eslint-disable */\n// @ts-nocheck\n// Generated by tauri-specta. Do not edit manually.\n",
                ),
            "../src/api/bindings.ts",
        )
        .expect("failed to export TypeScript bindings");

    // `mut` is only needed when the mcp-bridge feature reassigns below.
    #[cfg_attr(not(feature = "mcp-bridge"), allow(unused_mut))]
    let mut app_builder = tauri::Builder::default().plugin(tauri_plugin_dialog::init());

    // Dev-only: the MCP bridge plugin (behind the `mcp-bridge` cargo feature)
    // lets the Tauri MCP server drive the app for manual verification. Never
    // present in release builds.
    #[cfg(feature = "mcp-bridge")]
    {
        app_builder = app_builder.plugin(tauri_plugin_mcp_bridge::init());
    }

    app_builder
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            let app_data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&app_data_dir).ok();
            let home_dir = app.path().home_dir()?;

            let fetcher = Box::new(HttpFetcher::new(REGISTRY_URL));
            let skill_fetcher = Box::new(HttpSkillFetcher::new(GITHUB_API_BASE));
            app.manage(AppState::new(
                fetcher,
                skill_fetcher,
                app_data_dir,
                home_dir,
            ));
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running skill-cellar");
}
